/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/dedup/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/confidence-threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfidence"];
        put: operations["putConfidence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/dedup-threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/dedup-title-overlap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTitleOverlap"];
        put: operations["putTitleOverlap"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["index_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin/dedup-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dedupRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin/events/regenerate-bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkRegenerateEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin/settings/digest-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["saveDigestPrompt"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin/settings/digest-prompt/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetDigestPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin/settings/extraction-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["saveExtractionPrompt"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/admin/settings/extraction-prompt/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetExtractionPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/digests/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["newForm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/digests/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        /**
         * Deletes a digest.
         * @description Deletes a digest.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/events/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["eventDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/events/{uid}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerateEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sources"];
        put?: never;
        post: operations["addSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources/refetch-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refetchAllSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources/{uid}/refetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refetchSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources/{uid}/refetch-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["refetchForm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/sources/{uid}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggleSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["spec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddSourceForm: {
            /** Format: int64 */
            chatId?: number | null;
            title: string;
            username?: string | null;
        };
        BulkRegenForm: {
            /** Format: int32 */
            days: number;
        };
        /** @description v1 city slugs per Decision 0003 Appendix B. Wire format = slug (lowercase, kebab-case). */
        CityV1: {
            slug: string;
        };
        ConfidenceThresholdRequest: {
            /** Format: double */
            threshold: number;
        };
        ConfidenceThresholdResponse: {
            /** Format: double */
            threshold: number;
        };
        /** @description Micronaut converts ISO-8601 date strings from HTML to LocalDate natively. */
        CreateDigestForm: {
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
        };
        DedupRunForm: {
            startDate: string;
            endDate: string;
            preview?: boolean | null;
            /** Format: int32 */
            maxSources?: number | null;
        };
        DedupRunRequest: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            preview: boolean;
            /** Format: int32 */
            maxSources: number;
        };
        DedupRunResponse: {
            preview: boolean;
            /** Format: int32 */
            sourcesProcessed: number;
            /** Format: int32 */
            clustersFound: number;
            merges: components["schemas"]["MergeRecord"][];
            splits: components["schemas"]["SplitRecord"][];
            /** Format: int64 */
            elapsedMs: number;
        };
        DedupThresholdRequest: {
            /** Format: double */
            similarity: number;
        };
        DedupThresholdResponse: {
            /** Format: double */
            similarity: number;
            /** Format: double */
            distance: number;
        };
        Directions: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            mapsUrl: string;
        };
        /** @description Contract §2 list-item shape. */
        Event: {
            uid: string;
            title: string;
            description?: string | null;
            category: components["schemas"]["EventCategory"];
            tags: string[];
            city?: components["schemas"]["CityV1"] | null;
            location?: string | null;
            startsAt: string;
            endsAt?: string | null;
            allDay: boolean;
            timezone: string;
            price: components["schemas"]["Price"];
            source: components["schemas"]["SourceSummary"];
            language: components["schemas"]["LanguageTag"];
            status: components["schemas"]["EventStatus"];
            createdAt: string;
            updatedAt: string;
        };
        EventCategory: Record<string, never>;
        /** @description Contract §3 --- feed fields + details object. */
        EventDetail: {
            uid: string;
            title: string;
            description?: string | null;
            category: components["schemas"]["EventCategory"];
            tags: string[];
            city?: components["schemas"]["CityV1"] | null;
            location?: string | null;
            startsAt: string;
            endsAt?: string | null;
            allDay: boolean;
            timezone: string;
            price: components["schemas"]["Price"];
            source: components["schemas"]["SourceSummary"];
            language: components["schemas"]["LanguageTag"];
            status: components["schemas"]["EventStatus"];
            createdAt: string;
            updatedAt: string;
            details: components["schemas"]["EventDetailExtras"];
        };
        /** @description Contract §3 detail extras. v1 emits stubs for fields backed by columns that don't yet exist (longDescription, directions, organizer, images, links). */
        EventDetailExtras: {
            longDescription?: string | null;
            directions?: components["schemas"]["Directions"] | null;
            organizer?: components["schemas"]["Organizer"] | null;
            images: components["schemas"]["EventImage"][];
            links: components["schemas"]["EventLink"][];
        };
        EventImage: {
            url: string;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            blurhash?: string | null;
            alt?: string | null;
        };
        EventLink: {
            label: string;
            url: string;
        };
        /**
         * @description v1 event status. Mirrors event.status CHECK constraint.
         * @enum {string}
         */
        EventStatus: "live" | "cancelled" | "postponed";
        /** @description Contract §2 paginated response envelope. */
        EventsPage: {
            data: components["schemas"]["Event"][];
            page: components["schemas"]["PageMeta"];
        };
        FacetEntry_CityV1_: {
            value: components["schemas"]["CityV1"];
            /** Format: int64 */
            count: number;
        };
        FacetEntry_EventCategory_: {
            value: components["schemas"]["EventCategory"];
            /** Format: int64 */
            count: number;
        };
        FacetEntry_String_: {
            value: string;
            /** Format: int64 */
            count: number;
        };
        FacetTruncated: {
            categories: boolean;
            cities: boolean;
            tags: boolean;
        };
        /** @description Contract §4 facets. */
        Facets: {
            categories: components["schemas"]["FacetEntry_EventCategory_"][];
            cities: components["schemas"]["FacetEntry_CityV1_"][];
            tags: components["schemas"]["FacetEntry_String_"][];
            truncated: components["schemas"]["FacetTruncated"];
        };
        /** @description Contract §5 health. */
        Health: {
            status: string;
            /** Format: int64 */
            uptime: number;
            version: string;
            checkedAt: string;
        };
        /**
         * @description v1 language tag. Mirrors event.language CHECK constraint. Frontend tolerates a broader BCP 47 set; v1 emits these three.
         * @enum {string}
         */
        LanguageTag: "ru" | "en" | "sr";
        MergeRecord: {
            /** Format: uuid */
            winnerEventUid: string;
            winnerTitle: string;
            loserEventUids: string[];
            loserTitles: string[];
            /** Format: int32 */
            sourcesMoved: number;
        };
        MinTitleOverlapRequest: {
            /** Format: double */
            overlap: number;
        };
        MinTitleOverlapResponse: {
            /** Format: double */
            overlap: number;
        };
        "ModelAndView_Map_String.Object__": {
            view: string;
            model: {
                [key: string]: Record<string, never>;
            };
        };
        Organizer: {
            name: string;
            url?: string | null;
        };
        PageMeta: {
            nextCursor?: string | null;
            hasMore: boolean;
            /**
             * Format: int64
             * @description Total count of events matching filters (irrespective of cursor). null when not computed.
             */
            total?: number | null;
        };
        /** @description Contract §2 "price sub-schema". */
        Price: {
            kind: components["schemas"]["PriceKind"];
            /** Format: int64 */
            amount?: number | null;
            currency?: string | null;
            display: string;
        };
        /**
         * @description Price kind per contract §2 "price sub-schema".
         * @enum {string}
         */
        PriceKind: "free" | "paid" | "unknown";
        PromptRequest: {
            value: string;
        };
        RefetchForm: {
            /** Format: int32 */
            days: number;
        };
        ResolveForm: {
            channel: string;
        };
        /** @description Contract §2 source object. */
        SourceSummary: {
            url?: string | null;
            /** Format: int32 */
            count: number;
        };
        SplitRecord: {
            /** Format: uuid */
            originalEventUid: string;
            originalTitle: string;
            newEventUids: string[];
            newEventTitles: string[];
            /** Format: int32 */
            sourcesMoved: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DedupRunRequest"];
            };
        };
        responses: {
            /** @description run 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupRunResponse"];
                };
            };
        };
    };
    getConfidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description getConfidence 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfidenceThresholdResponse"];
                };
            };
        };
    };
    putConfidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfidenceThresholdRequest"];
            };
        };
        responses: {
            /** @description putConfidence 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfidenceThresholdResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description get 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupThresholdResponse"];
                };
            };
        };
    };
    put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DedupThresholdRequest"];
            };
        };
        responses: {
            /** @description put 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupThresholdResponse"];
                };
            };
        };
    };
    getTitleOverlap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description getTitleOverlap 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinTitleOverlapResponse"];
                };
            };
        };
    };
    putTitleOverlap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MinTitleOverlapRequest"];
            };
        };
        responses: {
            /** @description putTitleOverlap 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinTitleOverlapResponse"];
                };
            };
        };
    };
    index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description index 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    index_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description index_1 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    dedupRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["DedupRunForm"];
            };
        };
        responses: {
            /** @description dedupRun 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": Record<string, never>;
                };
            };
        };
    };
    bulkRegenerateEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["BulkRegenForm"];
            };
        };
        responses: {
            /** @description bulkRegenerateEvents 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    saveDigestPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequest"];
            };
        };
        responses: {
            /** @description saveDigestPrompt 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    resetDigestPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description resetDigestPrompt 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    saveExtractionPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequest"];
            };
        };
        responses: {
            /** @description saveExtractionPrompt 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    resetExtractionPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description resetExtractionPrompt 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description list 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["CreateDigestForm"];
            };
        };
        responses: {
            /** @description create 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": Record<string, never>;
                };
            };
        };
    };
    newForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description newForm 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description detail 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    delete: {
        parameters: {
            query: {
                /** @description "list" (default) returns 204 --- HTMX removes the table row inline. "detail" returns HX-Redirect --- HTMX navigates back to the list page. */
                from: string;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description delete 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events: {
        parameters: {
            query: {
                sort: string;
                dateCategory: string;
                tags?: string[] | null;
                city?: string | null;
                perPage: number;
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description events 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    eventDetail: {
        parameters: {
            query?: {
                regenError?: string | null;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description eventDetail 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    regenerateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description regenerateEvent 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sources 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    addSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AddSourceForm"];
            };
        };
        responses: {
            /** @description addSource 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    refetchAllSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RefetchForm"];
            };
        };
        responses: {
            /** @description refetchAllSources 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    resolveSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["ResolveForm"];
            };
        };
        responses: {
            /** @description resolveSource 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": components["schemas"]["ModelAndView_Map_String.Object__"];
                };
            };
        };
    };
    removeSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description removeSource 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refetchSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RefetchForm"];
            };
        };
        responses: {
            /** @description refetchSource 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": Record<string, never>;
                };
            };
        };
    };
    refetchForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description refetchForm 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": components["schemas"]["ModelAndView_Map_String.Object__"];
                };
            };
        };
    };
    toggleSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description toggleSource 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                category?: string | null;
                city?: string | null;
                tag?: string[] | null;
                tagMode?: string | null;
                from?: string | null;
                to?: string | null;
                sort?: string | null;
                limit?: number | null;
                cursor?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description list_1 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description get_1 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: {
                category?: string | null;
                city?: string | null;
                tag?: string[] | null;
                tagMode?: string | null;
                from?: string | null;
                to?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description get_2 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description get_3 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    spec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description spec 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
}
